export const CARD_SPINNER_DESK_SIZE = 256;
export const CARD_SPINNER_INNER_CARD_SIZE_RATIO = 0.6;
export const CARD_SPINNER_INNER_CARD_SIZE =
  CARD_SPINNER_DESK_SIZE * CARD_SPINNER_INNER_CARD_SIZE_RATIO;
